In [3]:
import numpy as np

x1 = np.array([10, 20, 30], float)

In [8]:

# 有一個一維陣列x1，我分別想要把它變成一個 3*1 的矩陣x2，以及 1*3 的矩陣x3，作法如下。

print("shape of x1 is ", x1.shape)
print(x1)

print("-------------")

x2 = x1[:, np.newaxis]
print("shape of x2 is ", x2.shape)
print(x2)

print("-------------")

x3 = x1[np.newaxis, :]
print("shape of x3 is ", x3.shape)
print(x3)


shape of x1 is  (3,)
[ 10.  20.  30.]
-------------
shape of x2 is  (3, 1)
[[ 10.]
 [ 20.]
 [ 30.]]
-------------
shape of x3 is  (1, 3)
[[ 10.  20.  30.]]
